import iamges from "../../assets/img/images";

export const BestsellerData = [
  {
    index: 1,
    image: iamges.card1,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 2,
    image: iamges.card2,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 3,
    image: iamges.card3,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 4,
    image: iamges.card4,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 5,
    image: iamges.card5,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 6,
    image: iamges.card6,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 7,
    image: iamges.card7,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
  {
    index: 8,
    image: iamges.card8,
    title: "Graphic Design",
    department: "English Department",
    oldPrice: "$16.48",
    newPrice: "$6.48",
    colors: ["blue", "green", "orange", "black"],
  },
];
